# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 07:34
from __future__ import unicode_literals

import datetime
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateField()),
                ('shift', models.CharField(max_length=20)),
                ('machine', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('cash', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('cards', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('receipts', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('IOUs', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('cards_dtl', models.CharField(max_length=5000)),
                ('receipts_dtl', models.CharField(max_length=5000)),
                ('IOUs_dtl', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('created_time', models.DateField(default=datetime.date.today)),
                ('start_date', models.DateField(primary_key=True, serialize=False)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('bonus_salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('total_salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('actual_salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('comments', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='StaffSalary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=6)),
                ('bonus_salary', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_salary', models.DecimalField(decimal_places=2, max_digits=6)),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='n2cshiftapp.Salary')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('salary_rate', models.DecimalField(decimal_places=1, default=9, max_digits=3)),
            ],
        ),
        migrations.AddField(
            model_name='staffsalary',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salary',
            name='created_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='records',
            name='created_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
